//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFreshStore.Models.Context
{
    using System;
    using EntityModels;
    [Serializable]
    public partial class CorporateUser
    {
        public long Id { get; set; }
        public string EmployeeId { get; set; }
        public string Name { get; set; }
        public string MobileNo { get; set; }
        public string AlternativeMobileNo { get; set; }
        public string Email { get; set; }
        public string Designation { get; set; }
        public Nullable<long> CorporateContractId { get; set; }
        public string DeliveryAddress1 { get; set; }
        public string DeliveryAddress2 { get; set; }
        public Nullable<long> UserId { get; set; }
        public Nullable<long> CorporateDepartmentId { get; set; }
        public Nullable<long> CorporateDesignationId { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
    
        public virtual CorporateContract CorporateContract { get; set; }
        public virtual CorporateDepartment CorporateDepartment { get; set; }
        public virtual CorporateDesignation CorporateDesignation { get; set; }
        public virtual User User { get; set; }
    }
}
