//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFreshStore.Models.Context
{
    using System;
    using System.Collections.Generic;
    [Serializable]
    public partial class DistributorProductLine
    {
        public long Id { get; set; }
        public Nullable<long> DistributorId { get; set; }
        public Nullable<long> ProductLineId { get; set; }
    
        public virtual Distributor Distributor { get; set; }
        public virtual ProductLine ProductLine { get; set; }
    }
}
