//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFreshStore.Models.Context
{
    using System;
    using System.Collections.Generic;
    using EntityModels;
    [Serializable]
    public partial class MeghnaUser
    {
        public long Id { get; set; }
        public string EmployeeId { get; set; }
        public string Name { get; set; }
        public string MobileNo { get; set; }
        public string AlternativeMobileNo { get; set; }
        public string Email { get; set; }
        public string Designation { get; set; }
        public string DeliveryAddress1 { get; set; }
        public string DeliveryAddress2 { get; set; }
        public Nullable<long> UserId { get; set; }
        public Nullable<long> MeghnaDepartmentId { get; set; }
        public Nullable<long> MeghnaDesignationId { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public virtual MeghnaDepartment MeghnaDepartment { get; set; }
        public virtual MeghnaDesignation MeghnaDesignation { get; set; }
        public virtual User User { get; set; }
    }
}
