//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFreshStore.Models.Context
{
   
    using System;
    using System.Collections.Generic;

    [Serializable]
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.OrderDetails = new HashSet<OrderDetail>();
        }
    
        public long Id { get; set; }
        public string OrderNo { get; set; }
        public string CustomerName { get; set; }
        public string MobileNo { get; set; }
        public string Email { get; set; }
        public string UpdateAddress { get; set; }
        public string DeliveryAddress { get; set; }
        public Nullable<long> ThanaId { get; set; }
        public Nullable<long> MasterDepotId { get; set; }
        public Nullable<long> OrderStateId { get; set; }
        public Nullable<long> UserId { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public Nullable<long> OrderRejectId { get; set; }
        public string CouponCode { get; set; }
        public Nullable<decimal> CouponDiscount { get; set; }
        public decimal DeliveryCharge { get; set; }
        public string PaymentMethod { get; set; }
        public bool IsPaid { get; set; }
        public virtual MasterDepot MasterDepot { get; set; }
        public virtual OrderState OrderState { get; set; }
        public virtual Thana Thana { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
        public virtual OrderReject OrderReject { get; set; }
    }
}
