//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFreshStore.Models.Context
{
    using System;
    using System.Collections.Generic;
    [Serializable]
    public partial class OrderDetail
    {
        public long Id { get; set; }
        public Nullable<long> OrderId { get; set; }
        public Nullable<long> ProductUnitId { get; set; }
        public Nullable<long> ProductTypeId { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> DiscountPrice { get; set; }
        public Nullable<int> PacketQuantity { get; set; }
        public double DistributorPrice { get; set; }
        public string BrandName { get; set; }
        public string CategoryName { get; set; }
        public string Unit { get; set; }
        public virtual Order Order { get; set; }
        public virtual ProductUnit ProductUnit { get; set; }
    }
}
