//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFreshStore.Models.Context
{
    using System;
    using System.Collections.Generic;
    [Serializable]
    public partial class WishList
    {
        public long Id { get; set; }
        public long UserId { get; set; }
        public long ProductUnitId { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime AddedOn { get; set; }
        public Nullable<System.DateTime> DeletedOn { get; set; }
        public virtual ProductUnit ProductUnit { get; set; }
        public virtual User User { get; set; }
    }
}
